## Searching in arrays
### Where - get index
Search an array to see if a nelement is located in it or not

In [3]:
import numpy as np
arr1=np.array([1,2,3,4,5,6,7,8,9])
arr1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

### .where - basic use - search
To see where a specific element is located in array<br>
Takes a parameter arrayName and = element<br>
returns a tuple <br>
1st element-index<br>
IInd and so on element-afurther index at which element is located<br>

In [4]:
location=np.where(arr1==4)

In [5]:
location

(array([3]),)

In [6]:
arr1[2]=4

In [7]:
arr1

array([1, 2, 4, 4, 5, 6, 7, 8, 9])

In [8]:
location2=np.where(arr1==4)

In [9]:
location2

(array([2, 3]),)

### can also use where to check conditions

In [12]:
arr1

array([1, 2, 4, 4, 5, 6, 7, 8, 9])

In [13]:
less_than_five=np.where(arr1<5)
# Gives all indexes of elements less than 5

In [11]:
less_than_five

(array([0, 1, 2, 3]),)

In [14]:
div_by_three=np.where(arr1%3==0)
# Gives all indexes of elements divisible by 3

In [15]:
div_by_three

(array([5, 8]),)