# Numpy Basics
A library to work with arrays and perform operations on it<br>
import it as import numpy as np

## 1.Creating and Dimensional Arrays

### np.array()
pass a list to it

In [1]:
import numpy as np
l=[1,2,3,4,5]
a=np.array(l)
a

array([1, 2, 3, 4, 5])

### Dimensions of array <br>
Measure of sqaure brackets <br>
1. 1D array- 1 row
2. 2D array - 2 rows
3. 3D array - 3 rows

In [3]:
l2d=[[1,2,3,4,5],[6,7,8,9,10]]
a2d=np.array(l2d)
a2d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [41]:
l3d=[[[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]]]
a3d=np.array(l3d)
a3d

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15]]])

## Fiding dimesnion of a given array
#### ndim parameter
to check dimension of an array

In [42]:
a3d.ndim

3

In [43]:
a2d.ndim

2

### ndmin parameter 
To specify a dimension for an array

In [44]:
a4d=np.array(a3d,ndmin=5)

In [45]:
a4d

array([[[[[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10],
          [11, 12, 13, 14, 15]]]]])

In [46]:
a4d.ndim

5

## Indexing Arrays

Indexing changes according to Dimensions<br>


### 1D array
specify the index in square brackets

In [47]:
a

array([1, 2, 3, 4, 5])

In [48]:
a[4]

5

In [49]:
len(a)

5

In [50]:
a[3]

4

### 2D Arrays
[a,b] where a is the row and b is the column in the row

In [51]:
a2d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [52]:
a2d[1,4]

10

In [53]:
a2d[1,5]

IndexError: index 5 is out of bounds for axis 1 with size 5

In [54]:
a2d[0,2]

3

In [55]:
a2d[0,4]

5

### 3d Array
[a,b,c] 
where<br>
a = first dimension <br>
b=second dimension <br>
c=Thrid dimension

In [56]:
a3d

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15]]])

In [57]:
a3d.ndim

3

In [58]:
a3d[0,1,2]

8

In [32]:
a3d[0,0,1]

2

In [36]:
a3d[0,0,2]

3

a3d[0,0]

In [60]:
a3d[0,1]

array([ 6,  7,  8,  9, 10])

In [61]:
a3d[0,2]

array([11, 12, 13, 14, 15])

In [62]:
a3d[0,1,2]

8

In [63]:
a3d[0,2,3]

14

## Slicing Arrays

### 1D Arrays

In [67]:
a

array([1, 2, 3, 4, 5])

In [68]:
a_slice=a[0:3]

#### Slicing wont modify the original array unless we use equality sign

In [69]:
a_slice

array([1, 2, 3])

In [70]:
a

array([1, 2, 3, 4, 5])

In [71]:
b=a

In [72]:
b

array([1, 2, 3, 4, 5])

In [73]:
b=b[0:3]

In [74]:
b

array([1, 2, 3])

In [75]:
a

array([1, 2, 3, 4, 5])

#### Slicing with step , start end
##### start-end


In [79]:
a1=a[:]
a1

array([1, 2, 3, 4, 5])

##### Specific to end

In [80]:
a2=a[1:]
a2

array([2, 3, 4, 5])

##### start to specific

In [82]:
a3=a[:3]
a3

array([1, 2, 3])

### 2D arrays

In [83]:
a2d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [84]:
a2d1=a2d[0,0:2]

In [86]:
a2d1

array([1, 2])

In [87]:
a2d2=a2d[1,0:4]
a2d2

array([6, 7, 8, 9])

In [88]:
a22=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])

In [89]:
a22

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [90]:
a22_slice=a22[0:1,1:3]

In [91]:
a22_slice

array([[2, 3]])

In [92]:
a22_slice2=a22[0:2,1:3]

In [93]:
a22_slice2

array([[2, 3],
       [7, 8]])

In [94]:
a22_slice3=a22[0:3,:]
a22_slice3

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [95]:
a22_slice4=a22[0:3,:3]
a22_slice4

array([[ 1,  2,  3],
       [ 6,  7,  8],
       [11, 12, 13]])

### 3D Arrays

In [96]:
a3d

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15]]])

In [97]:
a3d_slice=a3d[0,0:2,1:3]
a3d_slice

array([[2, 3],
       [7, 8]])

In [98]:
a3d_slice2=a3d[0,0:3,1:5]
a3d_slice2

array([[ 2,  3,  4,  5],
       [ 7,  8,  9, 10],
       [12, 13, 14, 15]])

## Copy and View

In [102]:
a1

array([1, 2, 3, 4, 5])

### Copy
Used to create a copy of array<br>
Modifying original array wont affect copy

In [105]:
cp=a1.copy()
cp


array([1, 2, 3, 4, 5])

In [104]:
a1

array([1, 2, 3, 4, 5])

# Modifying array element
a1[0]=10
a1

In [107]:
#Elements in copy isnt changed
cp

array([1, 2, 3, 4, 5])

### View

Changing original array will affect view

In [110]:
vw=a1.view()

In [111]:
vw

array([10,  2,  3,  4,  5])

In [112]:
a1

array([10,  2,  3,  4,  5])

In [113]:
a1[3]=22

In [114]:
a1

array([10,  2,  3, 22,  5])

In [115]:
vw

array([10,  2,  3, 22,  5])

In [116]:
vw[2]=33

In [117]:
vw

array([10,  2, 33, 22,  5])

In [118]:
a1

array([10,  2, 33, 22,  5])

### To know wheher an array is a copy or view of original use

#### .base 
returns array for view but nothing for copy

In [119]:
vw.base

array([10,  2, 33, 22,  5])

In [122]:
cp

array([1, 2, 3, 4, 5])

In [123]:
cp.base

## Shaping and Reshaping array

### shape
To get shape of the array


In [126]:
a3d

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15]]])

In [128]:
a3d.shape

(1, 3, 5)

In [129]:
a2d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [130]:
a2d.shape

(2, 5)

In [131]:
a1

array([10,  2, 33, 22,  5])

In [132]:
a1.shape

(5,)

In [133]:
new_array=np.array([[1,2,3],[4,5,6,7]])

/tmp/ipykernel_14796/1532012740.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  new_array=np.array([[1,2,3],[4,5,6,7]])


In [134]:
new_array.shape

(2,)

## Reshapring array
### .reshape()

In [135]:
std=np.array([19,19,19,20,20,20,21,21,21])
exm_scr=np.array([57,60,65,72,75,78,82,84,87])

In [136]:
std

array([19, 19, 19, 20, 20, 20, 21, 21, 21])

In [137]:
exm_scr

array([57, 60, 65, 72, 75, 78, 82, 84, 87])

In [138]:
exm_scr_splt=exm_scr.reshape(3,3)

In [139]:
exm_scr_splt

array([[57, 60, 65],
       [72, 75, 78],
       [82, 84, 87]])

In [141]:
# The no of values in original array should match dimensions else it gives an error - ValueError

In [140]:
exm_scr_splt2=exm_scr.reshape(2,3)
exm_scr_splt2

ValueError: cannot reshape array of size 9 into shape (2,3)

In [142]:
exm_scr_splt3=exm_scr.reshape(9,1)
exm_scr_splt3

array([[57],
       [60],
       [65],
       [72],
       [75],
       [78],
       [82],
       [84],
       [87]])