# Numpy

1.A numeric computing Library to work with arrays , matrices and do advanced mathematical ad statistical operations on them.<br>
2.It can work with multi dimensional arrays and in domain of linear algebra, fourier transform, and matrices.<br>
3.Provides arrays that are much faster than lists.<br>
4.Arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.


#Creating an array

1.Import numpy as anything say np<br>

2.use np.array() function which takes a list as parameter for eg for a list [1,2,3,4] use the  np.array([1,2,3,4])

In [1]:
import numpy as np

l=[1,2,3,4]

a = np.array(l)
print(a)

[1 2 3 4]


# Checking dimensions
Dimensions ca be checked using the attribute
## 1. ndim
It can also be used to create an array with specific dimensions

In [2]:
c = np.array([[1, 2, 3], [4, 5, 6]])
print(f" The dimesions of array c is {c.ndim}") 

 The dimesions of array c is 2


In [3]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim) 

[[[[[1 2 3 4]]]]]
number of dimensions : 5


# Indexing Array elements
1.Array indexing is the same as accessing an array element.<br>

2.The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc.<br>

3.For multidimensional arrays say 2 dimensional arrays or matrices if we have to access the element at nth index of mth row <br>

    a.array[m][n]
    b.array[m,n]
    
4.Also supports negative indexing ie -1 will give last element

In [4]:
print(a[0])

1


In [5]:
print(a[2])

3


In [6]:
print(c[0][2])
print(c[1][2])

3
6


In [7]:
print(c[0,2])
print(c[1,2])

3
6


In [8]:
e = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(e[0, 1, 2]) 
print(e[0, 2, 2]) 

6


IndexError: index 2 is out of bounds for axis 1 with size 2

In [9]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1]) 

Last element from 2nd dim:  10


# Indexing in arrays

1.Slicing in python means taking elements from one given index to another given index.

2.We pass slice instead of index like this: [start:end].

3.We can also define the step, like this: [start:end:step]

4.Supports negative indexing i.e -1 gives last element

In [10]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5]) 
print(arr[:4]) 
print(arr[-3:-1])
print(arr[1:5:2]) 
print(arr[::2]) 


[2 3 4 5]
[1 2 3 4]
[5 6]
[2 4]
[1 3 5 7]


In [11]:
arr2 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr2[1, 1:4]) 

[7 8 9]


# DataTypes in Numpy

    i - integer
    b - boolean
    u - unsigned integer
    f - float
    c - complex float
    m - timedelta
    M - datetime
    O - object
    S - string
    U - unicode string
    V - fixed chunk of memory for other type ( void )
    
# dtype -Checking datatype
The NumPy array object has a property called dtype that returns the data type of the array:

# Creating Array With a Defined Data Type

We use the array() function to create arrays, this function can take an optional argument: dtype that allows us to define the expected data type of the array elements:


In [12]:
print(arr.dtype) 

int64


In [13]:
arr4 = np.array(['apple', 'banana', 'cherry'])

print(arr4.dtype) 

<U6


In [14]:
arr5 = np.array([1, 2, 3, 4], dtype='S')

print(arr5)
print(arr5.dtype) 

[b'1' b'2' b'3' b'4']
|S1


# Convert Data Type on Existing Arrays

## astype()- 
The astype() function creates a copy of the array, and allows you to specify the data type as a parameter.

In [15]:
arr6 = np.array([1.1, 2.1, 3.1])

newarr = arr6.astype('i')

print(newarr)
print(newarr.dtype) 

[1 2 3]
int32


In [16]:
arr7 = np.array([1.1, 2.1, 3.1])

newarr2 = arr7.astype(int)

print(newarr2)
print(newarr2.dtype) 

[1 2 3]
int64


# Reshaping

## np.reshape()

Takes a list of data and rshapes into certain dimensions we specify

3 Arguments<br>
1.Data<br>
2.Dimensions<br>
3.How to populate - row or columns C-row by row and F-column by column

In [18]:
arr7=np.reshape([1,2,3,4,5,6,7,8,9,10,11,12],[3,4],'C')

In [19]:
arr7

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [20]:
arr8=np.reshape([1,2,3,4,5,6,7,8,9,10,11,12],[3,4],'F')

In [21]:
arr8

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

# A BasketBall Dataset
A Dataset of following format

## Matrices:
### - Salary
### - Games
### - MinutesPlayed
### - FieldGoals
### - FieldGoalAttempts
### - Points
## Lists:
### - Players
### - Seasons
## Dictionaries:
### - Sdict
### - Pdict

In [22]:
#Comments:
#Seasons are labeled based on the first year in the season
#E.g. the 2012-2013 season is preseneted as simply 2012

#Notes and Corrections to the data:
#Kevin Durant: 2006 - College Data Used
#Kevin Durant: 2005 - Proxied With 2006 Data
#Derrick Rose: 2012 - Did Not Play
#Derrick Rose: 2007 - College Data Used
#Derrick Rose: 2006 - Proxied With 2007 Data
#Derrick Rose: 2005 - Proxied With 2007 Data

#Import numpy
import numpy as np

#Seasons
Seasons = ["2005","2006","2007","2008","2009","2010","2011","2012","2013","2014"]
Sdict = {"2005":0,"2006":1,"2007":2,"2008":3,"2009":4,"2010":5,"2011":6,"2012":7,"2013":8,"2014":9}

#Players
Players = ["KobeBryant","JoeJohnson","LeBronJames","CarmeloAnthony","DwightHoward","ChrisBosh","ChrisPaul","KevinDurant","DerrickRose","DwayneWade"]
Pdict = {"KobeBryant":0,"JoeJohnson":1,"LeBronJames":2,"CarmeloAnthony":3,"DwightHoward":4,"ChrisBosh":5,"ChrisPaul":6,"KevinDurant":7,"DerrickRose":8,"DwayneWade":9}

#Salaries
KobeBryant_Salary = [15946875,17718750,19490625,21262500,23034375,24806250,25244493,27849149,30453805,23500000]
JoeJohnson_Salary = [12000000,12744189,13488377,14232567,14976754,16324500,18038573,19752645,21466718,23180790]
LeBronJames_Salary = [4621800,5828090,13041250,14410581,15779912,14500000,16022500,17545000,19067500,20644400]
CarmeloAnthony_Salary = [3713640,4694041,13041250,14410581,15779912,17149243,18518574,19450000,22407474,22458000]
DwightHoward_Salary = [4493160,4806720,6061274,13758000,15202590,16647180,18091770,19536360,20513178,21436271]
ChrisBosh_Salary = [3348000,4235220,12455000,14410581,15779912,14500000,16022500,17545000,19067500,20644400]
ChrisPaul_Salary = [3144240,3380160,3615960,4574189,13520500,14940153,16359805,17779458,18668431,20068563]
KevinDurant_Salary = [0,0,4171200,4484040,4796880,6053663,15506632,16669630,17832627,18995624]
DerrickRose_Salary = [0,0,0,4822800,5184480,5546160,6993708,16402500,17632688,18862875]
DwayneWade_Salary = [3031920,3841443,13041250,14410581,15779912,14200000,15691000,17182000,18673000,15000000]
#Matrix
Salary = np.array([KobeBryant_Salary, JoeJohnson_Salary, LeBronJames_Salary, CarmeloAnthony_Salary, DwightHoward_Salary, ChrisBosh_Salary, ChrisPaul_Salary, KevinDurant_Salary, DerrickRose_Salary, DwayneWade_Salary])

#Games 
KobeBryant_G = [80,77,82,82,73,82,58,78,6,35]
JoeJohnson_G = [82,57,82,79,76,72,60,72,79,80]
LeBronJames_G = [79,78,75,81,76,79,62,76,77,69]
CarmeloAnthony_G = [80,65,77,66,69,77,55,67,77,40]
DwightHoward_G = [82,82,82,79,82,78,54,76,71,41]
ChrisBosh_G = [70,69,67,77,70,77,57,74,79,44]
ChrisPaul_G = [78,64,80,78,45,80,60,70,62,82]
KevinDurant_G = [35,35,80,74,82,78,66,81,81,27]
DerrickRose_G = [40,40,40,81,78,81,39,0,10,51]
DwayneWade_G = [75,51,51,79,77,76,49,69,54,62]
#Matrix
Games = np.array([KobeBryant_G, JoeJohnson_G, LeBronJames_G, CarmeloAnthony_G, DwightHoward_G, ChrisBosh_G, ChrisPaul_G, KevinDurant_G, DerrickRose_G, DwayneWade_G])

#Minutes Played
KobeBryant_MP = [3277,3140,3192,2960,2835,2779,2232,3013,177,1207]
JoeJohnson_MP = [3340,2359,3343,3124,2886,2554,2127,2642,2575,2791]
LeBronJames_MP = [3361,3190,3027,3054,2966,3063,2326,2877,2902,2493]
CarmeloAnthony_MP = [2941,2486,2806,2277,2634,2751,1876,2482,2982,1428]
DwightHoward_MP = [3021,3023,3088,2821,2843,2935,2070,2722,2396,1223]
ChrisBosh_MP = [2751,2658,2425,2928,2526,2795,2007,2454,2531,1556]
ChrisPaul_MP = [2808,2353,3006,3002,1712,2880,2181,2335,2171,2857]
KevinDurant_MP = [1255,1255,2768,2885,3239,3038,2546,3119,3122,913]
DerrickRose_MP = [1168,1168,1168,3000,2871,3026,1375,0,311,1530]
DwayneWade_MP = [2892,1931,1954,3048,2792,2823,1625,2391,1775,1971]
#Matrix
MinutesPlayed = np.array([KobeBryant_MP, JoeJohnson_MP, LeBronJames_MP, CarmeloAnthony_MP, DwightHoward_MP, ChrisBosh_MP, ChrisPaul_MP, KevinDurant_MP, DerrickRose_MP, DwayneWade_MP])

#Field Goals
KobeBryant_FG = [978,813,775,800,716,740,574,738,31,266]
JoeJohnson_FG = [632,536,647,620,635,514,423,445,462,446]
LeBronJames_FG = [875,772,794,789,768,758,621,765,767,624]
CarmeloAnthony_FG = [756,691,728,535,688,684,441,669,743,358]
DwightHoward_FG = [468,526,583,560,510,619,416,470,473,251]
ChrisBosh_FG = [549,543,507,615,600,524,393,485,492,343]
ChrisPaul_FG = [407,381,630,631,314,430,425,412,406,568]
KevinDurant_FG = [306,306,587,661,794,711,643,731,849,238]
DerrickRose_FG = [208,208,208,574,672,711,302,0,58,338]
DwayneWade_FG = [699,472,439,854,719,692,416,569,415,509]
#Matrix
FieldGoals  = np.array([KobeBryant_FG, JoeJohnson_FG, LeBronJames_FG, CarmeloAnthony_FG, DwightHoward_FG, ChrisBosh_FG, ChrisPaul_FG, KevinDurant_FG, DerrickRose_FG, DwayneWade_FG])

#Field Goal Attempts
KobeBryant_FGA = [2173,1757,1690,1712,1569,1639,1336,1595,73,713]
JoeJohnson_FGA = [1395,1139,1497,1420,1386,1161,931,1052,1018,1025]
LeBronJames_FGA = [1823,1621,1642,1613,1528,1485,1169,1354,1353,1279]
CarmeloAnthony_FGA = [1572,1453,1481,1207,1502,1503,1025,1489,1643,806]
DwightHoward_FGA = [881,873,974,979,834,1044,726,813,800,423]
ChrisBosh_FGA = [1087,1094,1027,1263,1158,1056,807,907,953,745]
ChrisPaul_FGA = [947,871,1291,1255,637,928,890,856,870,1170]
KevinDurant_FGA = [647,647,1366,1390,1668,1538,1297,1433,1688,467]
DerrickRose_FGA = [436,436,436,1208,1373,1597,695,0,164,835]
DwayneWade_FGA = [1413,962,937,1739,1511,1384,837,1093,761,1084]
#Matrix
FieldGoalAttempts = np.array([KobeBryant_FGA, JoeJohnson_FGA, LeBronJames_FGA, CarmeloAnthony_FGA, DwightHoward_FGA, ChrisBosh_FGA, ChrisPaul_FGA, KevinDurant_FGA, DerrickRose_FGA, DwayneWade_FGA])

#Points
KobeBryant_PTS = [2832,2430,2323,2201,1970,2078,1616,2133,83,782]
JoeJohnson_PTS = [1653,1426,1779,1688,1619,1312,1129,1170,1245,1154]
LeBronJames_PTS = [2478,2132,2250,2304,2258,2111,1683,2036,2089,1743]
CarmeloAnthony_PTS = [2122,1881,1978,1504,1943,1970,1245,1920,2112,966]
DwightHoward_PTS = [1292,1443,1695,1624,1503,1784,1113,1296,1297,646]
ChrisBosh_PTS = [1572,1561,1496,1746,1678,1438,1025,1232,1281,928]
ChrisPaul_PTS = [1258,1104,1684,1781,841,1268,1189,1186,1185,1564]
KevinDurant_PTS = [903,903,1624,1871,2472,2161,1850,2280,2593,686]
DerrickRose_PTS = [597,597,597,1361,1619,2026,852,0,159,904]
DwayneWade_PTS = [2040,1397,1254,2386,2045,1941,1082,1463,1028,1331]
#Matrix
Points = np.array([KobeBryant_PTS, JoeJohnson_PTS, LeBronJames_PTS, CarmeloAnthony_PTS, DwightHoward_PTS, ChrisBosh_PTS, ChrisPaul_PTS, KevinDurant_PTS, DerrickRose_PTS, DwayneWade_PTS])             
                  


In [23]:
Games

array([[80, 77, 82, 82, 73, 82, 58, 78,  6, 35],
       [82, 57, 82, 79, 76, 72, 60, 72, 79, 80],
       [79, 78, 75, 81, 76, 79, 62, 76, 77, 69],
       [80, 65, 77, 66, 69, 77, 55, 67, 77, 40],
       [82, 82, 82, 79, 82, 78, 54, 76, 71, 41],
       [70, 69, 67, 77, 70, 77, 57, 74, 79, 44],
       [78, 64, 80, 78, 45, 80, 60, 70, 62, 82],
       [35, 35, 80, 74, 82, 78, 66, 81, 81, 27],
       [40, 40, 40, 81, 78, 81, 39,  0, 10, 51],
       [75, 51, 51, 79, 77, 76, 49, 69, 54, 62]])

In [24]:
Players


['KobeBryant',
 'JoeJohnson',
 'LeBronJames',
 'CarmeloAnthony',
 'DwightHoward',
 'ChrisBosh',
 'ChrisPaul',
 'KevinDurant',
 'DerrickRose',
 'DwayneWade']

In [25]:
Pdict

{'KobeBryant': 0,
 'JoeJohnson': 1,
 'LeBronJames': 2,
 'CarmeloAnthony': 3,
 'DwightHoward': 4,
 'ChrisBosh': 5,
 'ChrisPaul': 6,
 'KevinDurant': 7,
 'DerrickRose': 8,
 'DwayneWade': 9}

In [26]:
Pdict['CarmeloAnthony']

3

In [27]:
Games[Pdict['CarmeloAnthony']]

array([80, 65, 77, 66, 69, 77, 55, 67, 77, 40])

In [28]:
Seasons


['2005',
 '2006',
 '2007',
 '2008',
 '2009',
 '2010',
 '2011',
 '2012',
 '2013',
 '2014']

In [29]:
Sdict['2008']

3

In [30]:
Games[Pdict['CarmeloAnthony']][Sdict['2008']]

66

## Field_Goals/Game every player played and rounding it using 
### np.matrix.round()
USed to round resultant value


In [31]:
import warnings
warnings.filterwarnings('ignore')

FieldGoals_Per_game=np.matrix.round(FieldGoals/Games)

In [32]:
FieldGoals_Per_game

array([[12., 11.,  9., 10., 10.,  9., 10.,  9.,  5.,  8.],
       [ 8.,  9.,  8.,  8.,  8.,  7.,  7.,  6.,  6.,  6.],
       [11., 10., 11., 10., 10., 10., 10., 10., 10.,  9.],
       [ 9., 11.,  9.,  8., 10.,  9.,  8., 10., 10.,  9.],
       [ 6.,  6.,  7.,  7.,  6.,  8.,  8.,  6.,  7.,  6.],
       [ 8.,  8.,  8.,  8.,  9.,  7.,  7.,  7.,  6.,  8.],
       [ 5.,  6.,  8.,  8.,  7.,  5.,  7.,  6.,  7.,  7.],
       [ 9.,  9.,  7.,  9., 10.,  9., 10.,  9., 10.,  9.],
       [ 5.,  5.,  5.,  7.,  9.,  9.,  8., nan,  6.,  7.],
       [ 9.,  9.,  9., 11.,  9.,  9.,  8.,  8.,  8.,  8.]])

## Summary Statistics
1.sum()-to find sum - has a parameter axis<br>
2.mean()- to find mean<br>
3.std-standard deviation<br>
4.var-variance<br>


In [33]:
Games

array([[80, 77, 82, 82, 73, 82, 58, 78,  6, 35],
       [82, 57, 82, 79, 76, 72, 60, 72, 79, 80],
       [79, 78, 75, 81, 76, 79, 62, 76, 77, 69],
       [80, 65, 77, 66, 69, 77, 55, 67, 77, 40],
       [82, 82, 82, 79, 82, 78, 54, 76, 71, 41],
       [70, 69, 67, 77, 70, 77, 57, 74, 79, 44],
       [78, 64, 80, 78, 45, 80, 60, 70, 62, 82],
       [35, 35, 80, 74, 82, 78, 66, 81, 81, 27],
       [40, 40, 40, 81, 78, 81, 39,  0, 10, 51],
       [75, 51, 51, 79, 77, 76, 49, 69, 54, 62]])

In [34]:
Games.sum()

6669

In [35]:
Games.mean()

66.69

In [36]:
Games.std()

17.735103608380754

In [37]:
Games.var()

314.5339

In [40]:
#axis 0-find sum column wise
Games.sum(axis=0)

array([701, 618, 716, 776, 728, 780, 560, 663, 596, 531])

In [41]:
#axis 1-find sum row wise
Games.sum(axis=1)

array([653, 739, 752, 673, 727, 684, 699, 639, 460, 643])

# Vectorised Operations

In [43]:
a=np.arange(10)

In [44]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
#Doesnt modify original array
a+10

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [46]:
a*10

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [48]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
b=np.arange(11,21)

In [55]:
b

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [59]:
c=a+b

In [57]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
b

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [60]:
c

array([11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

In [83]:
# Boolean arrays -returned by boolean operators

In [62]:
a>=2

array([False, False,  True,  True,  True,  True,  True,  True,  True,
        True])

In [70]:
b[b>12]

array([13, 14, 15, 16, 17, 18, 19, 20])

In [71]:
v=b>15

In [72]:
b[v]

array([16, 17, 18, 19, 20])

In [81]:
v=b>15

In [82]:
b[v]

array([16, 17, 18, 19, 20])

In [84]:
# Useful Python functions
